(cl:in-package cloud_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STARTRINGINDEX-VAL
          STARTRINGINDEX
          ENDRINGINDEX-VAL
          ENDRINGINDEX
          STARTORIENTATION-VAL
          STARTORIENTATION
          ENDORIENTATION-VAL
          ENDORIENTATION
          ORIENTATIONDIFF-VAL
          ORIENTATIONDIFF
          SEGMENTEDCLOUDGROUNDFLAG-VAL
          SEGMENTEDCLOUDGROUNDFLAG
          SEGMENTEDCLOUDCOLIND-VAL
          SEGMENTEDCLOUDCOLIND
          SEGMENTEDCLOUDRANGE-VAL
          SEGMENTEDCLOUDRANGE
          XM-VAL
          XM
          XM-VAL
          XM
          YM-VAL
          YM
          YM-VAL
          YM
          ZM-VAL
          ZM
          ZM-VAL
          ZM
))